# Generated by Django 3.1 on 2020-09-22 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('user', models.EmailField(max_length=50)),
            ],
            options={
                'db_table': 'Posts',
            },
        ),
    ]
