# Generated by Django 3.1 on 2020-09-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepost', '0002_posts_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
